<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
    One for Windows with net7.0-windows TFM, one for MacOS with net7.0-macos and one with net7.0 TFM for Linux.-->
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>2.0</Version>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  
  <ItemGroup>
    <!-- 保留 Serilog -->
    <TrimmerRootAssembly Include="Serilog" />
    <!-- 保留 Avalonia.Win32 -->
    <TrimmerRootAssembly Include="Avalonia.Win32" />
  </ItemGroup>
  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>$(Temp)\$(AssemblyName)</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\..\..\Release</OutputPath>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.0.7" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="HotAvalonia"  Version="3.0.0" PrivateAssets="All" Publish="True" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FzLib.Avalonia.Test.csproj" />
  </ItemGroup>
</Project>
