<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <Version>$(FzLibVersion)</Version>
    <PackageLicenseExpression>	Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>$(Temp)\$(AssemblyName)\Debug</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>$(Temp)\$(AssemblyName)\Release</OutputPath>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaXaml Remove="Test\**" />
    <Compile Remove="Test\**" />
    <EmbeddedResource Remove="Test\**" />
    <None Remove="Test\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="App.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="App.axaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Xaml.Behaviors.Interactivity" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FzLib\FzLib.csproj" />
  </ItemGroup>

</Project>
